//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockTrackerEntities : DbContext
    {
        public StockTrackerEntities()
            : base("name=StockTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<stock> stocks { get; set; }
        public DbSet<stock_history> stock_history { get; set; }
        public DbSet<hypothesis_result> hypothesis_result { get; set; }
        public DbSet<stockkdj> stockkdjs { get; set; }
        public DbSet<stockma> stockmas { get; set; }
        public DbSet<stockmacd> stockmacds { get; set; }
        public DbSet<stock_buysell_point> stock_buysell_point { get; set; }
        public DbSet<stock_trading_date> stock_trading_date { get; set; }
        public DbSet<stock_extend_info> stock_extend_info { get; set; }
        public DbSet<market_index> market_index { get; set; }
        public DbSet<market_index_history> market_index_history { get; set; }
        public DbSet<stock_category> stock_category { get; set; }
        public DbSet<stock_category_ref> stock_category_ref { get; set; }
        public DbSet<stock_income_statement_history> stock_income_statement_history { get; set; }
    }
}
