//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_index
    {
        public market_index()
        {
            this.market_index_history = new HashSet<market_index_history>();
        }
    
        public int id { get; set; }
        public string index_name { get; set; }
    
        public virtual ICollection<market_index_history> market_index_history { get; set; }
    }
}
