//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_index_history
    {
        public int id { get; set; }
        public Nullable<int> market_index_id { get; set; }
        public Nullable<int> trading_date_id { get; set; }
        public Nullable<decimal> min_price { get; set; }
        public Nullable<long> trade_num { get; set; }
        public Nullable<long> trade_money { get; set; }
        public Nullable<decimal> diff_money { get; set; }
        public Nullable<decimal> close_price { get; set; }
        public Nullable<decimal> open_price { get; set; }
        public Nullable<decimal> max_price { get; set; }
        public Nullable<decimal> diff_rate { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual stock_trading_date stock_trading_date { get; set; }
        public virtual market_index market_index { get; set; }
    }
}
