//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_category_ref
    {
        public int id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual stock_category stock_category { get; set; }
    }
}
