//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_extend_info
    {
        public int id { get; set; }
        public int stock_id { get; set; }
        public string company_fullname { get; set; }
        public Nullable<System.DateTime> listed_date { get; set; }
        public Nullable<long> general_capital { get; set; }
        public Nullable<long> circulation_capital { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string industry { get; set; }
        public string company_website { get; set; }
    
        public virtual stock stock { get; set; }
    }
}
