//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_trading_date
    {
        public stock_trading_date()
        {
            this.stock_history = new HashSet<stock_history>();
            this.stockkdjs = new HashSet<stockkdj>();
        }
    
        public int id { get; set; }
        public System.DateTime trading_date { get; set; }
    
        public virtual ICollection<stock_history> stock_history { get; set; }
        public virtual ICollection<stockkdj> stockkdjs { get; set; }
    }
}
