//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockma
    {
        public int id { get; set; }
        public int stock_id { get; set; }
        public System.DateTime stock_date { get; set; }
        public decimal ma5 { get; set; }
        public decimal ma10 { get; set; }
        public decimal ma20 { get; set; }
        public decimal ma30 { get; set; }
        public decimal ma60 { get; set; }
        public decimal ma120 { get; set; }
        public Nullable<int> ma20_raisedays { get; set; }
        public Nullable<int> ma20_dropdays { get; set; }
        public Nullable<int> ma30_raisedays { get; set; }
        public Nullable<int> ma30_dropdays { get; set; }
        public Nullable<int> stock_history_id { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual stock_history stock_history { get; set; }
    }
}
