//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_category
    {
        public stock_category()
        {
            this.stock_category_ref = new HashSet<stock_category_ref>();
        }
    
        public int id { get; set; }
        public string block_category { get; set; }
        public string child_category { get; set; }
        public string category_name { get; set; }
        public string category_code { get; set; }
    
        public virtual ICollection<stock_category_ref> stock_category_ref { get; set; }
    }
}
