//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_income_statement_history
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<decimal> revenue { get; set; }
        public Nullable<decimal> net_profit { get; set; }
        public Nullable<decimal> earnings_per_share { get; set; }
        public Nullable<decimal> total_assets { get; set; }
        public Nullable<int> shareholder_amount { get; set; }
    
        public virtual stock stock { get; set; }
    }
}
