//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_history
    {
        public stock_history()
        {
            this.stockkdjs = new HashSet<stockkdj>();
            this.stockmacds = new HashSet<stockmacd>();
            this.stockmas = new HashSet<stockma>();
            this.stock_buysell_point = new HashSet<stock_buysell_point>();
        }
    
        public int id { get; set; }
        public int stock_id { get; set; }
        public System.DateTime stock_day { get; set; }
        public decimal open_price { get; set; }
        public decimal close_price { get; set; }
        public decimal min_price { get; set; }
        public decimal max_price { get; set; }
        public long trade_num { get; set; }
        public decimal trade_money { get; set; }
        public Nullable<float> turnover { get; set; }
        public Nullable<float> swing { get; set; }
        public Nullable<float> diff_rate { get; set; }
        public Nullable<int> trading_date { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual ICollection<stockkdj> stockkdjs { get; set; }
        public virtual ICollection<stockmacd> stockmacds { get; set; }
        public virtual ICollection<stockma> stockmas { get; set; }
        public virtual ICollection<stock_buysell_point> stock_buysell_point { get; set; }
        public virtual stock_trading_date stock_trading_date { get; set; }
    }
}
