//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockkdj
    {
        public int id { get; set; }
        public int stock_id { get; set; }
        public System.DateTime stock_date { get; set; }
        public float k { get; set; }
        public float d { get; set; }
        public float j { get; set; }
        public float rsv { get; set; }
        public Nullable<int> stock_history_id { get; set; }
        public Nullable<int> trading_date { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual stock_history stock_history { get; set; }
        public virtual stock_trading_date stock_trading_date { get; set; }
    }
}
