//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockmacd
    {
        public int id { get; set; }
        public int stock_id { get; set; }
        public System.DateTime stock_day { get; set; }
        public float ema12 { get; set; }
        public float ema26 { get; set; }
        public float diff { get; set; }
        public float dea { get; set; }
        public float macd { get; set; }
        public Nullable<int> stock_history_id { get; set; }
    
        public virtual stock stock { get; set; }
        public virtual stock_history stock_history { get; set; }
    }
}
