//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_buysell_point
    {
        public int id { get; set; }
        public Nullable<int> buy_point { get; set; }
        public Nullable<int> sell_point { get; set; }
        public Nullable<int> stock_history_id { get; set; }
    
        public virtual stock_history stock_history { get; set; }
    }
}
